(() => {
  let audioContext=null,selectedUid=null,busy=false;
  const $=s=>document.querySelector(s);
  const NOTE_NAMES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
  const MAJOR_PROFILE=[6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88];
  const MINOR_PROFILE=[6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17];
  const MAJOR_CAMELOT=['8B','3B','10B','5B','12B','7B','2B','9B','4B','11B','6B','1B'];
  const MINOR_CAMELOT=['5A','12A','7A','2A','9A','4A','11A','6A','1A','8A','3A','10A'];
  const CUE_LABELS=['INTRO','BUILD','VOCAL','DROP 1','BREAK','DROP 2','MIX OUT','OUTRO'];

  function resample(input,sourceRate,targetRate=11025){if(sourceRate===targetRate)return input;const ratio=sourceRate/targetRate,out=new Float32Array(Math.max(1,Math.floor(input.length/ratio)));for(let i=0;i<out.length;i++){const pos=i*ratio,left=Math.floor(pos),right=Math.min(input.length-1,left+1),f=pos-left;out[i]=input[left]*(1-f)+input[right]*f;}return out;}
  function waveformFromSignal(signal,bars=220){const size=Math.max(1,Math.floor(signal.length/bars)),data=[];let max=0;for(let i=0;i<bars;i++){const s=i*size,e=Math.min(signal.length,s+size);let peak=0,sum=0,n=0;for(let j=s;j<e;j++){const v=Math.abs(signal[j]);peak=Math.max(peak,v);sum+=v;n++;}const v=peak*.72+(sum/Math.max(1,n))*.28;max=Math.max(max,v);data.push(v);}return data.map(v=>Math.round(Math.max(3,(v/Math.max(max,.0001))*100)));}

  function onsetEnvelope(signal,sampleRate,targetRate=8000){const x=resample(signal,sampleRate,targetRate),frame=1024,hop=256,env=[];let prev=0;for(let s=0;s+frame<x.length;s+=hop){let sum=0;for(let i=0;i<frame;i++){const v=x[s+i];sum+=v*v;}const rms=Math.sqrt(sum/frame);env.push(Math.max(0,rms-prev));prev=rms;}const mean=env.reduce((a,b)=>a+b,0)/Math.max(1,env.length);for(let i=0;i<env.length;i++)env[i]=Math.max(0,env[i]-mean*.55);return{env,targetRate,hop};}
  function detectTempoFromEnvelope(env,targetRate,hop){if(env.length<20)return{bpm:null,confidence:0};let bestBpm=null,best=-Infinity,second=-Infinity;for(let bpm=60;bpm<=180;bpm++){const lag=Math.max(1,Math.round((60*targetRate)/(bpm*hop)));let score=0,n=0;for(let i=lag;i<env.length;i++){score+=env[i]*env[i-lag];n++;}score/=Math.max(1,n);if(score>best){second=best;best=score;bestBpm=bpm;}else if(score>second)second=score;}if(!Number.isFinite(best)||best<=0)return{bpm:null,confidence:0};const contrast=Math.max(0,(best-second)/best);return{bpm:bestBpm,confidence:Math.round(Math.min(100,35+contrast*260))};}
  function detectBeatgrid(signal,sampleRate,bpm,duration){if(!bpm)return{firstBeat:null,downbeat:null,beatInterval:null,beatgrid:[]};const {env,targetRate,hop}=onsetEnvelope(signal,sampleRate),beatInterval=60/bpm,framesPerBeat=(beatInterval*targetRate)/hop;let bestPhase=0,bestScore=-Infinity;const phaseSteps=Math.max(8,Math.round(framesPerBeat));for(let p=0;p<phaseSteps;p++){let score=0,n=0;for(let k=p;k<env.length;k+=framesPerBeat){const idx=Math.round(k);for(let d=-1;d<=1;d++){const j=idx+d;if(j>=0&&j<env.length)score+=env[j]*(d===0?1:.55);}n++;}score/=Math.max(1,n);if(score>bestScore){bestScore=score;bestPhase=p;}}
    const firstBeat=Math.max(0,(bestPhase*hop)/targetRate);let bestBarShift=0,bestBarScore=-Infinity;for(let shift=0;shift<4;shift++){let score=0,n=0;for(let beat=shift;beat<Math.floor(duration/beatInterval)&&beat<256;beat+=4){const t=firstBeat+beat*beatInterval,idx=Math.round((t*targetRate/hop));if(idx>=0&&idx<env.length){score+=env[idx];n++;}}score/=Math.max(1,n);if(score>bestBarScore){bestBarScore=score;bestBarShift=shift;}}
    const downbeat=firstBeat+bestBarShift*beatInterval,beatgrid=[];for(let t=firstBeat,i=0;t<duration&&i<4096;t+=beatInterval,i++)beatgrid.push(Number(t.toFixed(4)));return{firstBeat:Number(firstBeat.toFixed(4)),downbeat:Number(downbeat.toFixed(4)),beatInterval:Number(beatInterval.toFixed(6)),beatsPerBar:4,beatgrid};}

  function goertzelPower(signal,start,length,sampleRate,frequency){const w=2*Math.PI*frequency/sampleRate,coeff=2*Math.cos(w);let s0=0,s1=0,s2=0;for(let i=0;i<length;i++){const n=start+i;if(n>=signal.length)break;const win=.5-.5*Math.cos(2*Math.PI*i/Math.max(1,length-1));s0=signal[n]*win+coeff*s1-s2;s2=s1;s1=s0;}return Math.max(0,s1*s1+s2*s2-coeff*s1*s2);}
  function correlation(a,b){const am=a.reduce((x,y)=>x+y,0)/a.length,bm=b.reduce((x,y)=>x+y,0)/b.length;let num=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-am,y=b[i]-bm;num+=x*y;da+=x*x;db+=y*y;}return num/Math.sqrt(Math.max(1e-12,da*db));}
  function rotateProfile(profile,root){return Array.from({length:12},(_,i)=>profile[(i-root+12)%12]);}
  function detectKey(signal,sampleRate){const targetRate=11025,x=resample(signal,sampleRate,targetRate),frame=4096,maxFrames=48,usable=Math.max(1,x.length-frame),step=Math.max(frame,Math.floor(usable/maxFrames)),chroma=new Array(12).fill(0);let frames=0;for(let start=0;start+frame<=x.length&&frames<maxFrames;start+=step,frames++){for(let pc=0;pc<12;pc++){let power=0;for(let octave=2;octave<=5;octave++){const midi=12*(octave+1)+pc,freq=440*Math.pow(2,(midi-69)/12);if(freq<targetRate/2)power+=Math.log1p(goertzelPower(x,start,frame,targetRate,freq));}chroma[pc]+=power;}}const sum=chroma.reduce((a,b)=>a+b,0);if(!sum)return{key:'—',confidence:0};const norm=chroma.map(v=>v/sum),c=[];for(let root=0;root<12;root++){c.push({score:correlation(norm,rotateProfile(MAJOR_PROFILE,root)),key:MAJOR_CAMELOT[root],name:`${NOTE_NAMES[root]} major`});c.push({score:correlation(norm,rotateProfile(MINOR_PROFILE,root)),key:MINOR_CAMELOT[root],name:`${NOTE_NAMES[root]} minor`});}c.sort((a,b)=>b.score-a.score);const best=c[0],runner=c[1],confidence=Math.round(Math.max(0,Math.min(100,45+(best.score-runner.score)*180+best.score*20)));return{key:best.key,keyName:best.name,confidence};}

  function snapToBar(target,downbeat,beatInterval,duration){if(!Number.isFinite(downbeat)||!beatInterval)return Math.max(0,Math.min(duration,target));const bar=beatInterval*4,n=Math.round((target-downbeat)/bar),t=downbeat+n*bar;return Math.max(0,Math.min(duration,Number(t.toFixed(3))));}
  function buildAutoCues(duration,grid,waveformData){const ratios=[.025,.16,.28,.39,.53,.66,.84,.965];return ratios.map((ratio,i)=>{let target=snapToBar(duration*ratio,grid.downbeat,grid.beatInterval,duration);if(waveformData?.length&&duration>0){const bar=grid.beatInterval*4,center=Math.round(target/duration*(waveformData.length-1)),radius=Math.max(1,Math.round((bar*2)/duration*waveformData.length));let best=center;for(let j=Math.max(0,center-radius);j<=Math.min(waveformData.length-1,center+radius);j++)if(waveformData[j]>waveformData[best])best=j;target=snapToBar((best/(waveformData.length-1))*duration,grid.downbeat,grid.beatInterval,duration);}return{index:i,label:CUE_LABELS[i],time:Number(target.toFixed(3)),source:'auto',locked:false};});}

  async function analyzeBlob(blob){audioContext||=new(window.AudioContext||window.webkitAudioContext)();const buffer=await audioContext.decodeAudioData(await blob.arrayBuffer()),maxSeconds=180,length=Math.min(buffer.length,Math.round(buffer.sampleRate*maxSeconds)),start=Math.max(0,Math.floor((buffer.length-length)/2)),mono=new Float32Array(length);for(let ch=0;ch<buffer.numberOfChannels;ch++){const channel=buffer.getChannelData(ch);for(let i=0;i<length;i++)mono[i]+=channel[start+i]/buffer.numberOfChannels;}const waveformData=waveformFromSignal(mono);let rms=0;for(const v of mono)rms+=v*v;rms=Math.sqrt(rms/Math.max(1,mono.length));const energyScore=Math.round(Math.max(0,Math.min(100,(20*Math.log10(Math.max(rms,1e-7))+60)*1.65))),env=onsetEnvelope(mono,buffer.sampleRate),tempo=detectTempoFromEnvelope(env.env,env.targetRate,env.hop),key=detectKey(mono,buffer.sampleRate),grid=detectBeatgrid(mono,buffer.sampleRate,tempo.bpm,buffer.duration),autoCues=buildAutoCues(buffer.duration,grid,waveformData),confidence=Math.round((tempo.confidence+key.confidence)/2);return{bpm:tempo.bpm,key:key.key,keyName:key.keyName,duration:buffer.duration,waveformData,energy:energyScore<35?'Low':energyScore<68?'Medium':'High',energyScore,danceability:tempo.confidence,analysisConfidence:confidence,analysisEngine:'Dawo Native Offline Beatgrid',analyzedAt:new Date().toISOString(),...grid,autoCues,cues:autoCues.map(c=>c.time)};}

  function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  async function render(){const rows=await window.DawoLibrary.all(),list=$('#analyzerTrackList'),count=$('#sharedLibraryCount');if(count)count.textContent=rows.length;if(!list)return;list.innerHTML=rows.length?rows.map(t=>`<button class="library-track ${selectedUid===t.uid?'selected':''}" data-analyzer-track="${escapeHtml(t.uid)}"><span><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.artist)} · ${t.source}</small></span><span class="track-analysis"><b>${t.bpm||'—'}</b><small>BPM</small></span><span class="track-analysis"><b>${escapeHtml(t.key||'—')}</b><small>KEY</small></span></button>`).join(''):'<div class="library-empty">Knihovna je prázdná. Přidej audio soubory nebo synchronizuj zdroje.</div>';document.querySelectorAll('[data-analyzer-track]').forEach(btn=>btn.addEventListener('click',()=>{selectedUid=btn.dataset.analyzerTrack;render();renderSelected();}));if(!selectedUid&&rows[0]){selectedUid=rows[0].uid;renderSelected();}}
  async function renderSelected(){const t=selectedUid?await window.DawoLibrary.get(selectedUid):null;$('#analysisTitle').textContent=t?.title||'Žádná skladba';$('#analysisArtist').textContent=t?.artist||'Vyber track ze společné knihovny';$('#analysisBpm').textContent=t?.bpm||'—';$('#analysisKey').textContent=t?.key||'—';$('#analysisEnergy').textContent=t?.energyScore!=null?`${t.energyScore}%`:'—';$('#analysisConfidence').textContent=t?.analysisConfidence!=null?`${t.analysisConfidence}%`:'—';if($('#analysisFirstBeat'))$('#analysisFirstBeat').textContent=t?.firstBeat!=null?`${t.firstBeat.toFixed(2)} s`:'—';if($('#analysisDownbeat'))$('#analysisDownbeat').textContent=t?.downbeat!=null?`${t.downbeat.toFixed(2)} s`:'—';const wave=$('#analysisWaveform');if(wave)wave.innerHTML=(t?.waveformData||[]).map(v=>`<i style="height:${Math.max(4,Number(v)||4)}%"></i>`).join('');const cue=$('#autoCueList');if(cue)cue.innerHTML=(t?.autoCues||[]).map(c=>`<div class="cue-chip"><b>${escapeHtml(c.label)}</b><span>${Number(c.time).toFixed(2)} s</span></div>`).join('')||'<div class="library-empty">Auto Cue Points vzniknou po analýze.</div>';const button=$('#analyzeSelectedButton');if(button)button.disabled=!t?.fileBlob||busy;}
  async function analyzeSelected(){if(busy||!selectedUid)return;const track=await window.DawoLibrary.get(selectedUid);if(!track?.fileBlob){alert('Tato skladba nemá uložený audio soubor.');return;}busy=true;$('#analyzeSelectedButton').textContent='Počítám beatgrid…';$('#analyzeSelectedButton').disabled=true;try{const result=await analyzeBlob(track.fileBlob);await window.DawoLibrary.update(track.uid,result);window.DawoMixStudio?.setStatus?.(`Beatgrid + Auto Cues: ${track.title} · ${result.bpm||'—'} BPM`);}catch(error){console.error(error);alert(`Analýza selhala: ${error.message}`);}finally{busy=false;$('#analyzeSelectedButton').textContent='Analyzovat vybranou';await render();await renderSelected();}}
  async function analyzeAll(){if(busy)return;const rows=(await window.DawoLibrary.all()).filter(t=>t.fileBlob);if(!rows.length){alert('Ve společné knihovně nejsou žádné analyzovatelné audio soubory.');return;}busy=true;try{for(let i=0;i<rows.length;i++){const t=rows[i];selectedUid=t.uid;$('#analyzeAllButton').textContent=`${i+1}/${rows.length}`;await renderSelected();try{await window.DawoLibrary.update(t.uid,await analyzeBlob(t.fileBlob));}catch(e){console.warn('Analysis failed',t.title,e);}}window.DawoMixStudio?.setStatus?.(`Beatgrid + Auto Cues dokončeny pro ${rows.length} skladeb`);}finally{busy=false;$('#analyzeAllButton').textContent='Analyzovat vše';await render();await renderSelected();}}
  async function addFiles(e){const files=[...(e.target.files||[])];if(!files.length)return;const added=await window.DawoLibrary.addFiles(files);selectedUid=added[0]?.uid||selectedUid;e.target.value='';await render();await renderSelected();}
  async function syncSources(){const result=await window.DawoLibrary.syncAllSources();window.DawoMixStudio?.setStatus?.(`Knihovna synchronizována · Playlist ${result.playlist} · Cues ${result.cues}`);await render();await renderSelected();}
  window.addEventListener('dawo-library-change',()=>{render();renderSelected();});window.addEventListener('DOMContentLoaded',()=>{$('#analyzerFiles')?.addEventListener('change',addFiles);$('#analyzeSelectedButton')?.addEventListener('click',analyzeSelected);$('#analyzeAllButton')?.addEventListener('click',analyzeAll);$('#syncLibraryButton')?.addEventListener('click',syncSources);syncSources().catch(console.warn);});window.DawoAnalyzer={render,analyzeSelected,analyzeAll,syncSources,analyzeBlob};
})();