(()=>{
let ctx,selectedUid,busy=false;const $=s=>document.querySelector(s),NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],MAJ=[6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88],MIN=[6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17],MAJC=['8B','3B','10B','5B','12B','7B','2B','9B','4B','11B','6B','1B'],MINC=['5A','12A','7A','2A','9A','4A','11A','6A','1A','8A','3A','10A'],LABELS=['INTRO','BUILD','VOCAL','DROP 1','BREAK','DROP 2','MIX OUT','OUTRO'];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function resample(x,sr,tr=11025){if(sr===tr)return x;const r=sr/tr,o=new Float32Array(Math.max(1,Math.floor(x.length/r)));for(let i=0;i<o.length;i++){const p=i*r,a=Math.floor(p),b=Math.min(x.length-1,a+1),f=p-a;o[i]=x[a]*(1-f)+x[b]*f}return o}
function waveform(x,n=220){const size=Math.max(1,Math.floor(x.length/n)),a=[];let mx=0;for(let i=0;i<n;i++){let peak=0,sum=0,c=0;for(let j=i*size;j<Math.min(x.length,(i+1)*size);j++){const v=Math.abs(x[j]);peak=Math.max(peak,v);sum+=v;c++}const q=peak*.72+(sum/Math.max(1,c))*.28;mx=Math.max(mx,q);a.push(q)}return a.map(v=>Math.round(Math.max(3,v/Math.max(mx,.0001)*100)))}
function envelope(x,sr,tr=8000){x=resample(x,sr,tr);const frame=1024,hop=256,e=[];let prev=0;for(let s=0;s+frame<x.length;s+=hop){let q=0;for(let i=0;i<frame;i++)q+=x[s+i]*x[s+i];const rms=Math.sqrt(q/frame);e.push(Math.max(0,rms-prev));prev=rms}const m=e.reduce((a,b)=>a+b,0)/Math.max(1,e.length);for(let i=0;i<e.length;i++)e[i]=Math.max(0,e[i]-m*.55);return{e,tr,hop}}
function tempo({e,tr,hop}){if(e.length<20)return{bpm:null,confidence:0};let bpm=null,best=-1,second=-1;for(let b=60;b<=180;b++){const lag=Math.max(1,Math.round(60*tr/(b*hop)));let s=0,n=0;for(let i=lag;i<e.length;i++){s+=e[i]*e[i-lag];n++}s/=Math.max(1,n);if(s>best){second=best;best=s;bpm=b}else if(s>second)second=s}return best>0?{bpm,confidence:Math.round(Math.min(100,35+Math.max(0,(best-second)/best)*260))}:{bpm:null,confidence:0}}
function beatgrid(begin,sr,bpm,duration){if(!bpm)return{firstBeat:null,downbeat:null,beatInterval:null,beatsPerBar:4,beatgrid:[]};const {e,tr,hop}=envelope(begin,sr),interval=60/bpm,fpb=interval*tr/hop,steps=Math.max(8,Math.round(fpb));let phase=0,best=-1;for(let p=0;p<steps;p++){let s=0,n=0;for(let k=p;k<e.length;k+=fpb){const z=Math.round(k);if(z<e.length){s+=e[z]+(e[z-1]||0)*.45+(e[z+1]||0)*.45;n++}}s/=Math.max(1,n);if(s>best){best=s;phase=p}}const first=phase*hop/tr;let shift=0,barBest=-1;for(let sh=0;sh<4;sh++){let s=0,n=0;for(let b=sh;b<Math.min(256,Math.floor((duration-first)/interval));b+=4){const z=Math.round((first+b*interval)*tr/hop);if(z<e.length){s+=e[z];n++}}s/=Math.max(1,n);if(s>barBest){barBest=s;shift=sh}}const down=first+shift*interval,g=[];for(let t=first,i=0;t<duration&&i<4096;t+=interval,i++)g.push(+t.toFixed(4));return{firstBeat:+first.toFixed(4),downbeat:+down.toFixed(4),beatInterval:+interval.toFixed(6),beatsPerBar:4,beatgrid:g}}
function gp(x,s,l,sr,f){const w=2*Math.PI*f/sr,k=2*Math.cos(w);let a=0,b=0,c=0;for(let i=0;i<l;i++){const n=s+i;if(n>=x.length)break;const win=.5-.5*Math.cos(2*Math.PI*i/Math.max(1,l-1));a=x[n]*win+k*b-c;c=b;b=a}return Math.max(0,b*b+c*c-k*b*c)}
function corr(a,b){const am=a.reduce((x,y)=>x+y,0)/a.length,bm=b.reduce((x,y)=>x+y,0)/b.length;let n=0,x=0,y=0;for(let i=0;i<a.length;i++){const p=a[i]-am,q=b[i]-bm;n+=p*q;x+=p*p;y+=q*q}return n/Math.sqrt(Math.max(1e-12,x*y))}
const rot=(p,r)=>Array.from({length:12},(_,i)=>p[(i-r+12)%12]);
function keyDetect(x,sr){const tr=11025;y=resample(x,sr,tr);const frame=4096,step=Math.max(frame,Math.floor(Math.max(1,y.length-frame)/48)),ch=new Array(12).fill(0);let frames=0;for(let s=0;s+frame<=y.length&&frames<48;s+=step,frames++)for(let pc=0;pc<12;pc++){let p=0;for(let o=2;o<=5;o++){const midi=12*(o+1)+pc,f=440*2**((midi-69)/12);if(f<tr/2)p+=Math.log1p(gp(y,s,frame,tr,f))}ch[pc]+=p}const sum=ch.reduce((a,b)=>a+b,0);if(!sum)return{key:'—',keyName:'',confidence:0};const norm=ch.map(v=>v/sum),all=[];for(let r=0;r<12;r++){all.push({score:corr(norm,rot(MAJ,r)),key:MAJC[r],name:`${NOTES[r]} major`},{score:corr(norm,rot(MIN,r)),key:MINC[r],name:`${NOTES[r]} minor`})}all.sort((a,b)=>b.score-a.score);const a=all[0],b=all[1];return{key:a.key,keyName:a.name,confidence:Math.round(Math.max(0,Math.min(100,45+(a.score-b.score)*180+a.score*20)))}}
function snap(t,g,d){if(!Number.isFinite(g.downbeat)||!g.beatInterval)return Math.max(0,Math.min(d,t));const bar=g.beatInterval*4;return Math.max(0,Math.min(d,+(g.downbeat+Math.round((t-g.downbeat)/bar)*bar).toFixed(3)))}
function autoCues(d,g,w){return[.025,.16,.28,.39,.53,.66,.84,.965].map((r,i)=>{let t=snap(d*r,g,d);if(w?.length&&d){const bar=g.beatInterval*4,c=Math.round(t/d*(w.length-1)),rad=Math.max(1,Math.round(bar*2/d*w.length));let best=c;for(let j=Math.max(0,c-rad);j<=Math.min(w.length-1,c+rad);j++)if(w[j]>w[best])best=j;t=snap(best/(w.length-1)*d,g,d)}return{index:i,label:LABELS[i],time:+t.toFixed(3),source:'auto',locked:false}})}
function monoRange(buffer,startSec,maxSec){const start=Math.max(0,Math.floor(startSec*buffer.sampleRate)),len=Math.min(buffer.length-start,Math.round(maxSec*buffer.sampleRate)),m=new Float32Array(Math.max(0,len));for(let ch=0;ch<buffer.numberOfChannels;ch++){const a=buffer.getChannelData(ch);for(let i=0;i<len;i++)m[i]+=a[start+i]/buffer.numberOfChannels}return m}
async function analyzeBlob(blob){ctx||=new(window.AudioContext||window.webkitAudioContext)();const b=await ctx.decodeAudioData(await blob.arrayBuffer()),begin=monoRange(b,0,180),center=monoRange(b,Math.max(0,b.duration/2-90),180),w=waveform(center),te=tempo(envelope(center,b.sampleRate)),kd=keyDetect(center,b.sampleRate),grid=beatgrid(begin,b.sampleRate,te.bpm,b.duration);let rms=0;for(const v of center)rms+=v*v;rms=Math.sqrt(rms/Math.max(1,center.length));const energyScore=Math.round(Math.max(0,Math.min(100,(20*Math.log10(Math.max(rms,1e-7))+60)*1.65))),cues=autoCues(b.duration,grid,w);return{bpm:te.bpm,key:kd.key,keyName:kd.keyName,duration:b.duration,waveformData:w,energy:energyScore<35?'Low':energyScore<68?'Medium':'High',energyScore,danceability:te.confidence,analysisConfidence:Math.round((te.confidence+kd.confidence)/2),analysisEngine:'Dawo Native Offline Beatgrid',analyzedAt:new Date().toISOString(),...grid,autoCues:cues,cues:cues.map(c=>c.time)}}
function ensureUI(){const metrics=$('.analysis-metrics');if(metrics&&!$('#analysisFirstBeat'))metrics.insertAdjacentHTML('beforeend','<article><small>FIRST BEAT</small><strong id="analysisFirstBeat">—</strong></article><article><small>DOWNBEAT</small><strong id="analysisDownbeat">—</strong></article>');const pane=$('.analysis-pane');if(pane&&!$('#autoCueList'))pane.insertAdjacentHTML('beforeend','<div style="margin-top:18px"><div class="pane-title" style="padding-left:0">AUTO CUE POINTS · SNAP TO BAR</div><div id="autoCueList" style="display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:8px"></div></div>')}
async function render(){const rows=await DawoLibrary.all(),list=$('#analyzerTrackList');if($('#sharedLibraryCount'))$('#sharedLibraryCount').textContent=rows.length;if(!list)return;list.innerHTML=rows.length?rows.map(t=>`<button class="library-track ${selectedUid===t.uid?'selected':''}" data-analyzer-track="${esc(t.uid)}"><span><strong>${esc(t.title)}</strong><small>${esc(t.artist)} · ${t.source}</small></span><span class="track-analysis"><b>${t.bpm||'—'}</b><small>BPM</small></span><span class="track-analysis"><b>${esc(t.key||'—')}</b><small>KEY</small></span></button>`).join(''):'<div class="library-empty">Knihovna je prázdná.</div>';document.querySelectorAll('[data-analyzer-track]').forEach(b=>b.onclick=()=>{selectedUid=b.dataset.analyzerTrack;render();renderSelected()});if(!selectedUid&&rows[0])selectedUid=rows[0].uid;renderSelected()}
async function renderSelected(){ensureUI();const t=selectedUid?await DawoLibrary.get(selectedUid):null;$('#analysisTitle').textContent=t?.title||'Žádná skladba';$('#analysisArtist').textContent=t?.artist||'Vyber track ze společné knihovny';$('#analysisBpm').textContent=t?.bpm||'—';$('#analysisKey').textContent=t?.key||'—';$('#analysisEnergy').textContent=t?.energyScore!=null?`${t.energyScore}%`:'—';$('#analysisConfidence').textContent=t?.analysisConfidence!=null?`${t.analysisConfidence}%`:'—';$('#analysisFirstBeat').textContent=t?.firstBeat!=null?`${Number(t.firstBeat).toFixed(2)} s`:'—';$('#analysisDownbeat').textContent=t?.downbeat!=null?`${Number(t.downbeat).toFixed(2)} s`:'—';$('#analysisWaveform').innerHTML=(t?.waveformData||[]).map(v=>`<i style="height:${Math.max(4,+v||4)}%"></i>`).join('');$('#autoCueList').innerHTML=(t?.autoCues||[]).map(c=>`<div style="padding:10px;border:1px solid #1d2a38;border-radius:9px;background:#09111a"><b style="display:block;color:#19e6ef;font-size:10px">${esc(c.label)}</b><span style="font-size:12px">${Number(c.time).toFixed(2)} s</span></div>`).join('')||'<div class="library-empty">Auto Cue Points vzniknou po analýze.</div>';$('#analyzeSelectedButton').disabled=!t?.fileBlob||busy}
async function analyzeSelected(){if(busy||!selectedUid)return;const t=await DawoLibrary.get(selectedUid);if(!t?.fileBlob)return alert('Tato skladba nemá uložený audio soubor.');busy=true;$('#analyzeSelectedButton').textContent='Počítám beatgrid…';try{const r=await analyzeBlob(t.fileBlob);await DawoLibrary.update(t.uid,r);DawoMixStudio?.setStatus?.(`Beatgrid + Auto Cues: ${t.title} · ${r.bpm||'—'} BPM`)}catch(e){console.error(e);alert(`Analýza selhala: ${e.message}`)}finally{busy=false;$('#analyzeSelectedButton').textContent='Analyzovat vybranou';await render()}}
async function analyzeAll(){if(busy)return;const rows=(await DawoLibrary.all()).filter(t=>t.fileBlob);if(!rows.length)return alert('Ve společné knihovně nejsou žádné analyzovatelné audio soubory.');busy=true;try{for(let i=0;i<rows.length;i++){selectedUid=rows[i].uid;$('#analyzeAllButton').textContent=`${i+1}/${rows.length}`;try{await DawoLibrary.update(rows[i].uid,await analyzeBlob(rows[i].fileBlob))}catch(e){console.warn(e)}}DawoMixStudio?.setStatus?.(`Beatgrid + Auto Cues dokončeny pro ${rows.length} skladeb`)}finally{busy=false;$('#analyzeAllButton').textContent='Analyzovat vše';await render()}}
async function syncSources(){const r=await DawoLibrary.syncAllSources();DawoMixStudio?.setStatus?.(`Knihovna synchronizována · Playlist ${r.playlist} · Cues ${r.cues}`);await render()}
window.addEventListener('dawo-library-change',render);window.addEventListener('DOMContentLoaded',()=>{ensureUI();$('#analyzerFiles')?.addEventListener('change',async e=>{const f=[...(e.target.files||[])];if(f.length){const a=await DawoLibrary.addFiles(f);selectedUid=a[0]?.uid||selectedUid;e.target.value='';render()}});$('#analyzeSelectedButton')?.addEventListener('click',analyzeSelected);$('#analyzeAllButton')?.addEventListener('click',analyzeAll);$('#syncLibraryButton')?.addEventListener('click',syncSources);syncSources().catch(console.warn)});window.DawoAnalyzer={render,analyzeSelected,analyzeAll,syncSources,analyzeBlob};
})();