(()=>{
  if(window.__dawoAutoMatch)return;window.__dawoAutoMatch=true;
  const $=s=>document.querySelector(s),QUEUE='dawo:workflow:analyzerQueue';
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const camelot=k=>{const m=String(k||'').toUpperCase().match(/^(1[0-2]|[1-9])([AB])$/);return m?{n:+m[1],l:m[2]}:null};
  const ringDiff=(a,b)=>Math.min(Math.abs(a-b),12-Math.abs(a-b));
  function keyScore(a,b){const x=camelot(a),y=camelot(b);if(!x||!y)return null;if(x.n===y.n&&x.l===y.l)return 100;if(x.l===y.l&&ringDiff(x.n,y.n)===1)return 94;if(x.n===y.n&&x.l!==y.l)return 88;if(x.l!==y.l&&ringDiff(x.n,y.n)===1)return 74;return Math.max(20,62-ringDiff(x.n,y.n)*9-(x.l!==y.l?8:0))}
  function bpmDelta(a,b){a=Number(a);b=Number(b);if(!(a>0&&b>0))return null;const opts=[b,b/2,b*2].map(v=>Math.abs(a-v));return Math.min(...opts)}
  function bpmScore(a,b){const d=bpmDelta(a,b);if(d==null)return null;return Math.max(0,100-d*9)}
  function energyScore(a,b){const x=Number(a),y=Number(b);if(!Number.isFinite(x)||!Number.isFinite(y))return null;return Math.max(0,100-Math.abs(x-y)*2.2)}
  function genreScore(a,b){const x=norm(a),y=norm(b);if(!x||!y)return null;if(x===y)return 100;if(x.includes(y)||y.includes(x))return 84;return 45}
  function score(a,b){const parts=[['Key',keyScore(a.key,b.key),.40],['BPM',bpmScore(a.bpm,b.bpm),.35],['Energy',energyScore(a.energyScore,b.energyScore),.20],['Genre',genreScore(a.genre,b.genre),.05]].filter(x=>x[1]!=null);const w=parts.reduce((s,x)=>s+x[2],0)||1;const total=Math.round(parts.reduce((s,x)=>s+x[1]*x[2],0)/w);return{total,parts,bpmDiff:bpmDelta(a.bpm,b.bpm)}}
  function style(){if($('#dawoAutoMatchStyle'))return;const s=document.createElement('style');s.id='dawoAutoMatchStyle';s.textContent=`
    .auto-match-btn{color:#9bc5d0!important}.auto-match-modal{position:fixed;inset:0;z-index:99999;background:#000a;display:grid;place-items:center;padding:18px}.auto-match-card{width:min(760px,100%);max-height:86vh;overflow:auto;border:1px solid var(--line);border-radius:18px;background:var(--panel);padding:18px;box-shadow:0 28px 80px #0009}.auto-match-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.auto-match-head h3{margin:0;font-size:20px}.auto-match-head p{margin:5px 0 0;color:var(--muted);font-size:11px}.auto-match-close{width:38px;height:38px;border:1px solid var(--line);border-radius:10px;background:#161b22;color:#ccd5de;cursor:pointer}.auto-match-list{display:grid;gap:9px;margin-top:16px}.auto-match-row{display:grid;grid-template-columns:68px minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:13px;background:#10151b}.auto-match-score{font-size:22px;font-weight:900;color:#78bea7}.auto-match-score small{display:block;font-size:8px;color:var(--muted)}.auto-match-title strong{display:block;font-size:12px}.auto-match-title small{display:block;margin-top:4px;color:var(--muted);font-size:9px}.auto-match-parts{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.auto-match-parts span{padding:4px 6px;border:1px solid #303945;border-radius:999px;color:#aeb8c2;font-size:8px}.auto-match-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.auto-match-actions button{padding:7px 9px;border:1px solid #37414d;border-radius:8px;background:#171d24;color:#d5dde5;font-size:9px;font-weight:800;cursor:pointer}.auto-match-actions button.primary{border-color:#426d60;background:#1d372f;color:#def3e9}@media(max-width:650px){.auto-match-row{grid-template-columns:58px 1fr}.auto-match-actions{grid-column:1/-1;justify-content:flex-start}}
  `;document.head.appendChild(s)}
  function install(){style();const bar=$('.library-module-toolbar');if(bar&&!$('#libraryAutoMatch')){const b=document.createElement('button');b.id='libraryAutoMatch';b.className='secondary-action';b.type='button';b.textContent='⤳ Auto Match';b.onclick=()=>{const ids=[...document.querySelectorAll('[data-library-select]:checked')].map(x=>x.dataset.librarySelect);if(ids.length!==1)return alert('Vyber přesně jednu skladbu jako výchozí track pro Auto Match.');open(ids[0])};bar.appendChild(b)}const rows=$('#libraryModuleRows');if(rows)rows.querySelectorAll('.library-module-row[data-library-uid]').forEach(r=>{const a=r.querySelector('.library-module-actions');if(!a||a.querySelector('.auto-match-btn'))return;const b=document.createElement('button');b.type='button';b.className='auto-match-btn';b.title='Auto Match – najít nejlepší další track';b.textContent='⤳';b.onclick=e=>{e.stopPropagation();open(r.dataset.libraryUid)};a.prepend(b)})}
  async function open(uid){const all=await DawoLibrary.all(),src=all.find(t=>String(t.uid)===String(uid));if(!src)return;const matches=all.filter(t=>t.uid!==src.uid).map(t=>({track:t,...score(src,t)})).sort((a,b)=>b.total-a.total).slice(0,12);const wrap=document.createElement('div');wrap.className='auto-match-modal';wrap.innerHTML=`<div class="auto-match-card"><div class="auto-match-head"><div><h3>Auto Match</h3><p>${esc(src.title||src.fileName)} · ${src.bpm||'—'} BPM · ${esc(src.key||'—')} → nejlepší další tracky</p></div><button class="auto-match-close">×</button></div><div class="auto-match-list">${matches.length?matches.map((m,i)=>row(src,m,i)).join(''):'<div style="color:var(--muted);padding:20px">V Library nejsou další tracky k porovnání.</div>'}</div></div>`;document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector('.auto-match-close').onclick=()=>wrap.remove();wrap.querySelectorAll('[data-match-analyze]').forEach(b=>b.onclick=()=>{sessionStorage.setItem(QUEUE,JSON.stringify([src.uid,b.dataset.matchAnalyze]));DawoMixStudio?.showPanel?.('analyzer');wrap.remove();DawoMixStudio?.setStatus?.('Auto Match dvojice otevřena v Analyzeru')});wrap.querySelectorAll('[data-match-playlist]').forEach(b=>b.onclick=()=>playlistChooser(b.dataset.matchPlaylist,wrap));}
  function row(src,m,i){const t=m.track,parts=m.parts.map(p=>`<span>${p[0]} ${Math.round(p[1])}%</span>`).join('');return `<div class="auto-match-row"><div class="auto-match-score">${m.total}%<small>MATCH</small></div><div class="auto-match-title"><strong>${i+1}. ${esc(t.title||t.fileName||'Bez názvu')}</strong><small>${esc(t.artist||'—')} · ${t.bpm||'—'} BPM · ${esc(t.key||'—')}${m.bpmDiff!=null?` · Δ ${m.bpmDiff.toFixed(1)} BPM`:''}</small><div class="auto-match-parts">${parts}</div></div><div class="auto-match-actions"><button data-match-analyze="${esc(t.uid)}">Analyzer</button><button class="primary" data-match-playlist="${esc(t.uid)}">＋ Playlist</button></div></div>`}
  function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open('DawoMixPlaylistStudioDB',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('playlists'))r.result.createObjectStore('playlists',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  const req=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
  async function playlistChooser(uid,parent){const db=await openDb(),list=await req(db.transaction('playlists').objectStore('playlists').getAll());db.close();if(!list.length)return alert('Nejdřív vytvoř playlist v Playlist Creatoru.');const name=prompt('Do kterého playlistu?\n'+list.map((p,i)=>`${i+1}. ${p.name}`).join('\n'),'1');const idx=Number(name)-1,p=list[idx];if(!p)return;const d=await openDb();p.trackUids=[...new Set([...(p.trackUids||[]),uid])];p.updatedAt=new Date().toISOString();await req(d.transaction('playlists','readwrite').objectStore('playlists').put(p));d.close();DawoMixStudio?.setStatus?.(`Auto Match: track přidán do ${p.name}`);parent?.remove()}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install):install();new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
  window.DawoAutoMatch={open,score};
})();