(()=>{
  if(window.__dawoMegaConnect)return;window.__dawoMegaConnect=true;
  const $=s=>document.querySelector(s),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let megaFiles=[];
  const mime=name=>/\.mp3$/i.test(name)?'audio/mpeg':/\.wav$/i.test(name)?'audio/wav':/\.flac$/i.test(name)?'audio/flac':/\.m4a$/i.test(name)?'audio/mp4':/\.ogg$/i.test(name)?'audio/ogg':'audio/aiff';
  function style(){if($('#dawoMegaStyle'))return;const s=document.createElement('style');s.id='dawoMegaStyle';s.textContent=`
    #libraryMegaConnect{border-color:#7b4fd0!important;color:#d9c9ff!important;background:#171321!important}.mega-modal{position:fixed;inset:0;z-index:100020;background:#000b;display:grid;place-items:center;padding:16px}.mega-card{width:min(820px,100%);max-height:90vh;overflow:auto;border:1px solid var(--line);border-radius:18px;background:var(--panel);padding:18px;box-shadow:0 30px 90px #000a}.mega-head{display:flex;justify-content:space-between;gap:16px}.mega-head h3{margin:0;font-size:21px}.mega-head p{margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.45}.mega-close{width:38px;height:38px;border:1px solid var(--line);border-radius:10px;background:#171c22;color:#dce4eb}.mega-status{margin:14px 0;padding:11px 12px;border:1px solid #303947;border-radius:11px;background:#11171d;color:#cfd7df;font-size:10px}.mega-login-grid{display:grid;grid-template-columns:1fr 1fr 120px;gap:8px}.mega-login-grid input,.mega-link-row input,.mega-search{height:42px;border:1px solid #303946;border-radius:10px;background:#10151b;color:#eef3f6;padding:0 11px}.mega-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.mega-actions button,.mega-link-row button,.mega-import-selected{min-height:38px;padding:0 12px;border:1px solid #3b4651;border-radius:9px;background:#171d24;color:#dbe3ea;font-size:9px;font-weight:800;cursor:pointer}.mega-actions .primary,.mega-import-selected{border-color:#6549a8;background:#261d3b;color:#eee6ff}.mega-link-row{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px}.mega-list{margin-top:12px;border:1px solid #29333e;border-radius:11px;overflow:hidden;max-height:360px;overflow-y:auto}.mega-row{display:grid;grid-template-columns:24px 1fr;gap:9px;align-items:center;padding:9px 11px;border-bottom:1px solid #252e38;background:#10151b}.mega-row:last-child{border-bottom:0}.mega-row strong{display:block;font-size:10px}.mega-row small{display:block;color:var(--muted);font-size:8px;margin-top:2px;word-break:break-all}.mega-bottom{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:10px}.mega-web-note{padding:12px;border:1px solid #3a334b;border-radius:11px;background:#16121e;color:#b8adca;font-size:10px;line-height:1.5}.mega-progress{color:#9ec8b8;font-size:10px}@media(max-width:680px){.mega-login-grid{grid-template-columns:1fr}.mega-link-row{grid-template-columns:1fr}.mega-bottom{align-items:stretch;flex-direction:column}}
  `;document.head.appendChild(s)}
  function install(){style();const bar=$('.library-module-toolbar');if(!bar||$('#libraryMegaConnect'))return;const b=document.createElement('button');b.id='libraryMegaConnect';b.className='secondary-action';b.type='button';b.textContent='＋ MEGA';b.onclick=open;const add=bar.querySelector('.file-action');add?.after(b)}
  function open(){document.querySelector('.mega-modal')?.remove();const desktop=!!window.DawoDesktop?.isDesktop,wrap=document.createElement('div');wrap.className='mega-modal';wrap.innerHTML=`<div class="mega-card"><div class="mega-head"><div><h3>MEGA Connect</h3><p>${desktop?'Přihlášení a import audio souborů z MEGA Cloud Drive přes oficiální MEGAcmd.':'Webová verze může otevřít MEGA login, ale kvůli izolaci prohlížeče nemůže číst přihlášený Cloud Drive. Pro přímý account import použij desktop verzi.'}</p></div><button class="mega-close">×</button></div><div id="megaBody"></div></div>`;document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector('.mega-close').onclick=()=>wrap.remove();desktop?renderDesktop($('#megaBody')):renderWeb($('#megaBody'))}
  async function renderDesktop(host){host.innerHTML=`<div id="megaStatus" class="mega-status">Kontroluji MEGAcmd…</div><div class="mega-login-grid"><input id="megaEmail" type="email" placeholder="MEGA email"><input id="megaPassword" type="password" placeholder="Heslo"><input id="megaMfa" inputmode="numeric" placeholder="2FA (volitelné)"></div><div class="mega-actions"><button id="megaLogin" class="primary">Přihlásit</button><button id="megaRefresh">Načíst Cloud Drive</button><button id="megaLogout">Odhlásit</button><button id="megaInstallCmd">Nainstalovat MEGAcmd</button></div><div class="mega-link-row"><input id="megaPublicLink" placeholder="Veřejný MEGA file/folder link"><button id="megaImportLink">Importovat odkaz</button></div><input id="megaSearch" class="mega-search" style="width:100%;margin-top:12px" placeholder="Hledat v MEGA audio souborech…"><div id="megaList" class="mega-list"></div><div class="mega-bottom"><span id="megaProgress" class="mega-progress"></span><button id="megaImportSelected" class="mega-import-selected">Importovat vybrané do Library</button></div>`;$('#megaLogin').onclick=login;$('#megaRefresh').onclick=loadCloud;$('#megaLogout').onclick=logout;$('#megaInstallCmd').onclick=()=>DawoDesktop.megaOpenCmdDownload();$('#megaImportLink').onclick=()=>importRemote($('#megaPublicLink').value.trim());$('#megaImportSelected').onclick=importSelected;$('#megaSearch').oninput=draw;await status()}
  async function status(){const el=$('#megaStatus');try{const s=await DawoDesktop.megaStatus();el.textContent=!s.installed?'MEGAcmd není nainstalované. Klikni na „Nainstalovat MEGAcmd“.':s.loggedIn?`Přihlášeno: ${s.user}`:'MEGAcmd je připravené · účet není přihlášen.';if(s.loggedIn)loadCloud()}catch(e){el.textContent=`MEGA chyba: ${e.message}`}}
  async function login(){const email=$('#megaEmail').value.trim(),password=$('#megaPassword').value,mfa=$('#megaMfa').value.trim();if(!email||!password)return alert('Zadej MEGA email a heslo.');$('#megaStatus').textContent='Přihlašuji…';try{await DawoDesktop.megaLogin(email,password,mfa);$('#megaPassword').value='';await status()}catch(e){$('#megaStatus').textContent=`Přihlášení selhalo: ${e.message}`}}
  async function logout(){try{await DawoDesktop.megaLogout();megaFiles=[];draw();await status()}catch(e){alert(`Odhlášení selhalo: ${e.message}`)}}
  async function loadCloud(){const p=$('#megaProgress');p.textContent='Načítám audio soubory z MEGA…';try{megaFiles=await DawoDesktop.megaListAudio();p.textContent=`Nalezeno ${megaFiles.length} audio souborů`;draw()}catch(e){p.textContent=`Načtení selhalo: ${e.message}`}}
  function draw(){const list=$('#megaList');if(!list)return;const q=($('#megaSearch')?.value||'').toLowerCase(),rows=megaFiles.filter(x=>x.toLowerCase().includes(q));list.innerHTML=rows.length?rows.map((x,i)=>`<label class="mega-row"><input type="checkbox" data-mega-path="${esc(x)}"><span><strong>${esc(x.split('/').pop()||x)}</strong><small>${esc(x)}</small></span></label>`).join(''):'<div style="padding:20px;color:var(--muted);font-size:10px">Žádné audio soubory.</div>'}
  async function importSelected(){const paths=[...document.querySelectorAll('[data-mega-path]:checked')].map(x=>x.dataset.megaPath);if(!paths.length)return alert('Vyber alespoň jeden soubor.');await importMany(paths)}
  async function importRemote(remote){if(!remote)return alert('Vlož MEGA odkaz nebo vzdálenou cestu.');await importMany([remote])}
  async function importMany(paths){const progress=$('#megaProgress');let imported=0;for(let i=0;i<paths.length;i++){progress.textContent=`MEGA import ${i+1}/${paths.length}…`;let pack;try{pack=await DawoDesktop.megaDownload(paths[i]);const files=[];for(const p of pack.files||[]){const data=await DawoDesktop.readBinaryFile(p),name=String(p).split(/[\\/]/).pop()||'track';files.push(new File([data],name,{type:mime(name)}))}if(files.length){await DawoLibrary.addFiles(files);imported+=files.length}}catch(e){console.error(e);alert(`MEGA import selhal pro ${paths[i]}: ${e.message}`)}finally{if(pack?.dir)DawoDesktop.megaCleanup(pack.dir).catch(()=>{})}}progress.textContent=`Hotovo · importováno ${imported} audio souborů`;DawoMixStudio?.setStatus?.(`MEGA: importováno ${imported} audio souborů do Library`)}
  function renderWeb(host){host.innerHTML=`<div class="mega-web-note"><b>Webový režim</b><br>DawoMix otevře oficiální MEGA login v novém okně. Samotná GitHub Pages aplikace ale kvůli bezpečnostní izolaci nemůže po přihlášení procházet obsah účtu. Přímý Cloud Drive import funguje v DawoMixStudio Desktop s MEGAcmd.</div><div class="mega-actions"><button id="megaWebLogin" class="primary">Přihlásit na mega.nz</button></div><div class="mega-link-row"><input id="megaWebLink" placeholder="Veřejný MEGA odkaz"><button id="megaWebOpen">Otevřít odkaz v MEGA</button></div><label class="file-action" style="display:inline-flex;margin-top:12px">＋ Importovat stažené audio<input id="megaWebFiles" type="file" accept="audio/*" multiple hidden></label>`;$('#megaWebLogin').onclick=()=>window.open('https://mega.nz/login','_blank','noopener');$('#megaWebOpen').onclick=()=>{const u=$('#megaWebLink').value.trim();if(u)window.open(u,'_blank','noopener')};$('#megaWebFiles').onchange=async e=>{const files=[...(e.target.files||[])];if(files.length)await DawoLibrary.addFiles(files);e.target.value=''}}
  function boot(){install();new MutationObserver(install).observe(document.body,{childList:true,subtree:true})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();