const tabs=[...document.querySelectorAll('.tab')];const sideItems=[...document.querySelectorAll('.side-item')];const panels=[...document.querySelectorAll('.panel')];const status=document.querySelector('#status');const badge=document.querySelector('#transferBadge');const activeLabel=document.querySelector('#activeModuleLabel');const startModule=document.querySelector('#startModule');const compactSidebar=document.querySelector('#compactSidebar');const rememberModule=document.querySelector('#rememberModule');const labels={home:'Home',dawomix:'Playlist Creator',analyzer:'Analyzer',cueflow:'Cue Point Editor','tag-editor':'Tag Editor',traktor:'Traktor Tools',settings:'Settings'};
function setStatus(text){if(status)status.textContent=text}
function showPanel(id,{persist=true}={}){if(!document.getElementById(id))return;tabs.forEach(tab=>tab.classList.toggle('active',tab.dataset.target===id));sideItems.forEach(item=>item.classList.toggle('active',item.dataset.target===id));panels.forEach(panel=>panel.classList.toggle('active',panel.id===id));if(id==='cueflow'&&badge)badge.hidden=true;if(activeLabel)activeLabel.textContent=labels[id]||id;setStatus(`${labels[id]||id} připraven`);if(persist&&rememberModule?.checked)localStorage.setItem('dawo:lastModule',id);if(['home','tag-editor','traktor','settings'].includes(id))refreshSharedViews();if(id==='traktor')initTraktorTools().catch(console.warn)}
function bindTargets(){document.querySelectorAll('[data-target]').forEach(el=>el.addEventListener('click',()=>showPanel(el.dataset.target)))}bindTargets();
document.querySelector('#fullscreenBtn')?.addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){console.warn(e)}});
const savedStart=localStorage.getItem('dawo:startModule');if(savedStart&&startModule)startModule.value=savedStart;startModule?.addEventListener('change',()=>localStorage.setItem('dawo:startModule',startModule.value));const compactSaved=localStorage.getItem('dawo:compactSidebar')==='1';if(compactSidebar){compactSidebar.checked=compactSaved;document.body.classList.toggle('compact',compactSaved);compactSidebar.addEventListener('change',()=>{document.body.classList.toggle('compact',compactSidebar.checked);localStorage.setItem('dawo:compactSidebar',compactSidebar.checked?'1':'0')})}const rememberSaved=localStorage.getItem('dawo:rememberModule');if(rememberModule){rememberModule.checked=rememberSaved===null?true:rememberSaved==='1';rememberModule.addEventListener('change',()=>localStorage.setItem('dawo:rememberModule',rememberModule.checked?'1':'0'))}const initial=(rememberModule?.checked&&localStorage.getItem('dawo:lastModule'))||savedStart||'dawomix';showPanel(initial,{persist:false});
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey){const map={'1':'dawomix','2':'analyzer','3':'cueflow','4':'tag-editor','5':'traktor','6':'settings'};if(map[e.key]){e.preventDefault();showPanel(map[e.key])}}});

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tagSelectedUid=null;
async function refreshSharedViews(){if(!window.DawoLibrary)return;const rows=await window.DawoLibrary.all();['homeLibraryCount','footerLibraryCount'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=id==='footerLibraryCount'?`${rows.length} tracků`:rows.length});['tagLibraryState','traktorLibraryState','settingsLibraryState'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=`${rows.length} TRACKS`});const analyzed=rows.filter(t=>t.bpm||(t.key&&t.key!=='—')).length;const cues=rows.reduce((sum,t)=>sum+(Array.isArray(t.cues)?t.cues.filter(v=>v!=null).length:0),0);const a=document.getElementById('traktorAnalysisStats');if(a)a.textContent=`${analyzed} analyzovaných tracků`;const c=document.getElementById('traktorCueStats');if(c)c.textContent=`${cues} uložených cue bodů`;renderTagList(rows)}
function renderTagList(rows){const list=document.getElementById('tagTrackList');if(!list)return;if(!tagSelectedUid&&rows[0])tagSelectedUid=rows[0].uid;list.innerHTML=rows.length?rows.map(t=>`<div class="mock-row ${t.uid===tagSelectedUid?'active':''}" data-tag-track="${esc(t.uid)}"><strong>${esc(t.title)}</strong><small>${esc(t.artist)} · ${t.bpm||'—'} BPM · ${esc(t.key||'—')}</small></div>`).join(''):'<div class="library-empty">Knihovna je prázdná.</div>';document.querySelectorAll('[data-tag-track]').forEach(el=>el.addEventListener('click',()=>{tagSelectedUid=el.dataset.tagTrack;refreshSharedViews();loadTagTrack()}));loadTagTrack()}
async function loadTagTrack(){if(!tagSelectedUid||!window.DawoLibrary)return;const t=await window.DawoLibrary.get(tagSelectedUid);if(!t)return;document.getElementById('tagUid').value=t.uid;document.getElementById('tagTitle').value=t.title||'';document.getElementById('tagArtist').value=t.artist||'';document.getElementById('tagAlbum').value=t.album||'';document.getElementById('tagBpm').value=t.bpm||'';document.getElementById('tagKey').value=t.key==='—'?'':t.key||'';document.getElementById('tagGenre').value=t.genre||''}
document.getElementById('tagEditorForm')?.addEventListener('submit',async e=>{e.preventDefault();const uid=document.getElementById('tagUid').value;if(!uid)return;await window.DawoLibrary.update(uid,{title:document.getElementById('tagTitle').value.trim(),artist:document.getElementById('tagArtist').value.trim(),album:document.getElementById('tagAlbum').value.trim(),bpm:Number(document.getElementById('tagBpm').value)||null,key:document.getElementById('tagKey').value.trim()||'—',genre:document.getElementById('tagGenre').value.trim()});setStatus('Metadata uložena do společné knihovny');refreshSharedViews()});
async function syncLibrary(){const result=await window.DawoLibrary.syncAllSources();setStatus(`Knihovna synchronizována · Playlist ${result.playlist} · Cues ${result.cues}`);await refreshSharedViews();window.DawoAnalyzer?.render?.();return result}
document.getElementById('traktorSyncButton')?.addEventListener('click',syncLibrary);document.getElementById('settingsSyncLibrary')?.addEventListener('click',syncLibrary);document.getElementById('clearSharedLibrary')?.addEventListener('click',async()=>{if(!confirm('Vymazat společnou cache? Původní databáze Playlist Creator a Cue Point Editor zůstanou zachované.'))return;await window.DawoLibrary.clear();await refreshSharedViews();setStatus('Společná cache vymazána')});
document.getElementById('exportLibraryButton')?.addEventListener('click',async()=>{const rows=await window.DawoLibrary.all();const safe=rows.map(({fileBlob,sourceRecord,...track})=>track);const blob=new Blob([JSON.stringify({format:'DawoMixSharedLibrary',version:1,exportedAt:new Date().toISOString(),tracks:safe},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dawomix-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus(`Exportováno ${safe.length} tracků do JSON`)});

let traktorExporterPromise=null;
function ensureTraktorExporter(){if(window.DawoTraktorNml)return Promise.resolve(window.DawoTraktorNml);if(traktorExporterPromise)return traktorExporterPromise;traktorExporterPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='traktor-nml.js';script.onload=()=>window.DawoTraktorNml?resolve(window.DawoTraktorNml):reject(new Error('Traktor NML exporter se nenačetl.'));script.onerror=()=>reject(new Error('Soubor traktor-nml.js se nepodařilo načíst.'));document.head.appendChild(script)});return traktorExporterPromise}
async function initTraktorTools(){const exporter=await ensureTraktorExporter();const panel=document.getElementById('traktor');if(!panel||document.getElementById('traktorExportNmlButton'))return exporter;const cards=panel.querySelectorAll('.tool-cards article');const target=cards[2]||cards[0];const box=document.createElement('div');box.style.cssText='display:grid;gap:8px;margin-top:14px';box.innerHTML='<input id="traktorMusicFolder" type="text" placeholder="C:\\Users\\...\\Music" aria-label="Windows složka hudby" style="width:100%;padding:10px;border:1px solid #263442;border-radius:8px;background:#07101a;color:#eef7fb;outline:none"><button id="traktorExportNmlButton" class="primary-action" type="button">Export Traktor Pro 4 (.nml)</button><small style="color:#718697;line-height:1.4">Zadej základní Windows složku, kde má Traktor audio soubory. BPM, grid anchor a Hot Cues se vezmou ze společné knihovny.</small>';target.appendChild(box);const input=box.querySelector('#traktorMusicFolder');input.value=localStorage.getItem('dawo:traktorMusicFolder')||'';input.addEventListener('change',()=>localStorage.setItem('dawo:traktorMusicFolder',input.value.trim()));box.querySelector('#traktorExportNmlButton').addEventListener('click',exportSharedLibraryToTraktor);return exporter}
async function exportSharedLibraryToTraktor(){const exporter=await ensureTraktorExporter();const rows=await window.DawoLibrary.all();if(!rows.length){alert('Společná knihovna je prázdná.');return}const folder=(document.getElementById('traktorMusicFolder')?.value||localStorage.getItem('dawo:traktorMusicFolder')||'').trim();localStorage.setItem('dawo:traktorMusicFolder',folder);try{const result=exporter.download(rows,{musicFolder:folder,filename:`DawoMixStudio-Traktor-Pro-4-${new Date().toISOString().slice(0,10)}.nml`});const cueCount=rows.reduce((sum,t)=>sum+exporter.normalizeCues(t).filter(v=>v!=null).length,0);const gridCount=rows.filter(t=>Number.isFinite(Number(t.downbeat??t.firstBeat))&&Number(t.bpm)>0).length;setStatus(`Traktor NML: ${result.count} tracků · ${cueCount} hot cues · ${gridCount} beatgrid anchorů`)}catch(error){console.error(error);alert(`Traktor export selhal: ${error.message}`)}}

function installCueflowSharedSync(){const frame=document.getElementById('cueflow');if(!frame)return;try{const w=frame.contentWindow;if(!w)return;if(typeof w.saveTrack==='function'&&!w.__dawoSharedSyncInstalled){const original=w.saveTrack;w.saveTrack=async function(track){const result=await original(track);try{if(track?.sharedUid&&window.DawoLibrary?.update){const cueLabels=['INTRO','BUILD','VOCAL','DROP 1','BREAK','DROP 2','MIX OUT','OUTRO'];const cues=Array.from({length:8},(_,i)=>Number.isFinite(Number(track.cues?.[i]))?Number(track.cues[i]):null);await window.DawoLibrary.update(track.sharedUid,{cues,autoCues:cues.map((time,index)=>({index,label:cueLabels[index],time,source:'manual',locked:time!=null})),cueSource:'manual',cuesEditedAt:new Date().toISOString(),cueReady:cues.every(v=>v!=null),firstBeat:track.firstBeat??null,downbeat:track.downbeat??null,beatInterval:track.beatInterval??null,beatsPerBar:track.beatsPerBar||4,beatgrid:Array.isArray(track.beatgrid)?track.beatgrid:[],bpm:Number(track.bpm)||null,key:track.key||'—',waveformData:track.wave||null});setStatus(`${track.title}: ruční cue pointy synchronizovány`);await refreshSharedViews();window.DawoAnalyzer?.render?.()}}catch(error){console.error('CueFlow → Shared Library sync failed',error);setStatus(`${track?.title||'Track'}: cue pointy uloženy, synchronizace selhala`)}return result};w.__dawoSharedSyncInstalled=true}ensureTraktorExporter().then(exporter=>{w.createTraktorNml=function(selected,name='CUEFLOW výběr'){const folder=localStorage.getItem('dawo:traktorMusicFolder')||'';return exporter.createCollection(selected,{musicFolder:folder,collectionName:name})};w.__dawoTraktorExporterInstalled=true}).catch(console.warn)}catch(error){console.warn('CueFlow sync install failed',error)}}
const cueFrame=document.getElementById('cueflow');cueFrame?.addEventListener('load',()=>setTimeout(installCueflowSharedSync,0));setTimeout(installCueflowSharedSync,600);
window.addEventListener('dawo-library-change',refreshSharedViews);
window.addEventListener('DOMContentLoaded',()=>{syncLibrary().catch(()=>refreshSharedViews());installCueflowSharedSync();initTraktorTools().catch(console.warn)});

window.DawoMixStudio={showPanel,setStatus,syncLibrary,installCueflowSharedSync,exportSharedLibraryToTraktor,initTraktorTools,async transferPlaylist(playlist){const cueflow=document.querySelector('#cueflow');const bridge=cueflow.contentWindow?.CueflowBridge;if(!bridge){setStatus('Cue Point Editor se ještě načítá…');setTimeout(()=>window.DawoMixStudio.transferPlaylist(playlist),500);return}setStatus(`Přenáším „${playlist.name}“…`);try{const count=await bridge.importPlaylist(playlist);setStatus(`Přeneseno: ${playlist.name} (${count} skladeb)`);badge.hidden=false;await syncLibrary();showPanel('cueflow')}catch(error){console.error(error);setStatus('Přenos se nezdařil');alert(`Playlist se nepodařilo přenést: ${error.message}`)}},async transferToDawomix(payload){const dawomix=document.querySelector('#dawomix');const bridge=dawomix.contentWindow?.DawomixBridge;if(!bridge)throw new Error('Playlist Creator ještě není připravený');setStatus(`Posílám ${payload.tracks.length} skladeb do Playlist Creator…`);const result=await bridge.importFromCueflow(payload);await syncLibrary();setStatus(`Playlist Creator: vytvořen playlist „${result.name}“`);showPanel('dawomix');return result}};