(() => {
  const palette=value=>{const v=Math.max(0,Math.min(100,Number(value)||0));if(v<28)return'#35d7ff';if(v<45)return'#725cff';if(v<62)return'#a64ce3';if(v<74)return'#e0bd45';if(v<86)return'#e36635';return'#cf3d50'};
  function smooth(values){return values.map((_,i)=>{let s=0,n=0;for(let j=Math.max(0,i-3);j<=Math.min(values.length-1,i+3);j++){s+=values[j];n++}return s/Math.max(1,n)})}
  function recolor(container){if(!container)return;const bars=[...container.querySelectorAll(':scope > i')];if(!bars.length)return;const raw=bars.map(b=>Math.max(0,Math.min(100,parseFloat(b.style.height)||20))),vals=smooth(raw);container.classList.add('energy-spectrum');bars.forEach((bar,i)=>{const c=palette(vals[i]);bar.style.setProperty('--energy-color',c);bar.style.background=c;bar.style.boxShadow=`0 0 5px ${c}55`;bar.style.borderRadius='1px';bar.style.opacity='1'})}
  function mainStyle(){if(document.getElementById('dawoEnergyStyle'))return;const s=document.createElement('style');s.id='dawoEnergyStyle';s.textContent=`
.brand{min-width:96px;width:96px;padding:4px 8px!important;display:flex!important;align-items:center;justify-content:center;overflow:visible}
.brand .dawo-keywheel-wrap{width:68px;height:68px;border-radius:50%;display:flex;align-items:center;justify-content:center;filter:drop-shadow(0 0 10px #21dfff55);transition:transform .18s ease,filter .18s ease}
.brand:hover .dawo-keywheel-wrap{transform:scale(1.05);filter:drop-shadow(0 0 14px #21dfff88)}
.brand .dawo-keywheel-logo{width:100%;height:100%;display:block;object-fit:contain}
.analysis-waveform.energy-spectrum{position:relative;gap:2px!important;background:linear-gradient(180deg,#05090e,#09111a)!important;overflow:hidden}
.analysis-waveform.energy-spectrum:after{content:"";position:absolute;left:0;right:0;top:50%;height:1px;background:#27354099;pointer-events:none}
.analysis-waveform.energy-spectrum i{min-width:2px!important;max-width:5px;flex:1!important;background:var(--energy-color)!important;box-shadow:0 0 5px var(--energy-color)!important;opacity:1!important}
@media(max-width:760px){.brand{min-width:72px;width:72px}.brand .dawo-keywheel-wrap{width:54px;height:54px}}
`;document.head.appendChild(s)}
  function brand(){const b=document.querySelector('.brand');if(!b||b.dataset.logoInstalled)return;b.innerHTML='<span class="dawo-keywheel-wrap"><img class="dawo-keywheel-logo" src="key-wheel.svg" alt="Camelot Key Wheel"></span>';b.dataset.logoInstalled='1'}
  function loadIconPack(){if(document.querySelector('script[data-dawo-icon-pack]'))return;const script=document.createElement('script');script.src='icon-pack.js';script.dataset.dawoIconPack='1';document.body.appendChild(script)}
  function mainWave(){const w=document.getElementById('analysisWaveform');if(!w)return;recolor(w);new MutationObserver(()=>recolor(w)).observe(w,{childList:true})}
  function cueStyle(doc){if(doc.getElementById('dawoCueEnergyStyle'))return;const s=doc.createElement('style');s.id='dawoCueEnergyStyle';s.textContent='#waveform,#playerWaveform{align-items:center!important;gap:2px!important}#waveform.energy-spectrum,#playerWaveform.energy-spectrum{background:linear-gradient(180deg,#05090e,#09111a)!important}#waveform.energy-spectrum i,#playerWaveform.energy-spectrum i{background:var(--energy-color)!important;box-shadow:0 0 4px var(--energy-color)!important;border-radius:1px!important;opacity:1!important;min-width:2px}#waveform.energy-spectrum i.past,#playerWaveform.energy-spectrum i.past{filter:brightness(.55) saturate(.8)!important;opacity:.8!important;min-width:2px}';doc.head.appendChild(s)}
  function cueFrame(){const frame=document.getElementById('cueflow');if(!frame)return;const setup=()=>{try{const doc=frame.contentDocument;if(!doc)return;cueStyle(doc);const apply=()=>{recolor(doc.getElementById('waveform'));recolor(doc.getElementById('playerWaveform'))};apply();if(!doc.__dawoEnergyObserver){const o=new MutationObserver(apply);o.observe(doc.body,{childList:true,subtree:true});doc.__dawoEnergyObserver=o}}catch(e){console.warn('CueFlow energy spectrum style failed',e)}};frame.addEventListener('load',()=>setTimeout(setup,100));setTimeout(setup,700)}
  function playlistFrame(){const frame=document.getElementById('dawomix');if(!frame)return;const setup=()=>{try{const doc=frame.contentDocument;if(!doc||!doc.body)return;const add=(src,key)=>{if(doc.querySelector(`script[data-${key}]`))return;const script=doc.createElement('script');script.src=src;script.setAttribute(`data-${key}`,'1');doc.body.appendChild(script)};add('../playlist-modern.js','dawo-playlist-modern');setTimeout(()=>add('../playlist-download.js','dawo-playlist-download'),80)}catch(e){console.warn('Playlist modern UI failed',e)}};frame.addEventListener('load',()=>setTimeout(setup,120));setTimeout(setup,800)}
  function boot(){mainStyle();brand();loadIconPack();mainWave();cueFrame();playlistFrame();window.addEventListener('dawo-library-change',()=>setTimeout(()=>recolor(document.getElementById('analysisWaveform')),0))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();