(() => {
  const palette=value=>{const v=Math.max(0,Math.min(100,Number(value)||0));if(v<28)return'#35d7ff';if(v<45)return'#725cff';if(v<62)return'#a64ce3';if(v<74)return'#e0bd45';if(v<86)return'#e36635';return'#cf3d50'};
  function smooth(values){return values.map((_,i)=>{let s=0,n=0;for(let j=Math.max(0,i-3);j<=Math.min(values.length-1,i+3);j++){s+=values[j];n++}return s/Math.max(1,n)})}
  function recolor(container){if(!container)return;const bars=[...container.querySelectorAll(':scope > i')];if(!bars.length)return;const raw=bars.map(b=>Math.max(0,Math.min(100,parseFloat(b.style.height)||20))),vals=smooth(raw);container.classList.add('energy-spectrum');bars.forEach((bar,i)=>{const c=palette(vals[i]);bar.style.setProperty('--energy-color',c);bar.style.background=c;bar.style.boxShadow=`0 0 5px ${c}55`;bar.style.borderRadius='1px';bar.style.opacity='1'})}
  function mainStyle(){if(document.getElementById('dawoEnergyStyle'))return;const s=document.createElement('style');s.id='dawoEnergyStyle';s.textContent=`.brand{min-width:205px}.brand .dawo-custom-logo{width:116px;height:58px;object-fit:contain;filter:drop-shadow(0 0 9px #19e6ef66)}.brand .dawo-custom-sub{font-size:9px;letter-spacing:.28em;color:#66eaf0;font-weight:900;margin-left:2px}.analysis-waveform.energy-spectrum{position:relative;gap:2px!important;background:linear-gradient(180deg,#05090e,#09111a)!important;overflow:hidden}.analysis-waveform.energy-spectrum:after{content:"";position:absolute;left:0;right:0;top:50%;height:1px;background:#27354099;pointer-events:none}.analysis-waveform.energy-spectrum i{min-width:2px!important;max-width:5px;flex:1!important;background:var(--energy-color)!important;box-shadow:0 0 5px var(--energy-color)!important;opacity:1!important}@media(max-width:760px){.brand .dawo-custom-logo{width:92px;height:50px}.brand .dawo-custom-sub{display:none}}`;document.head.appendChild(s)}
  function brand(){const b=document.querySelector('.brand');if(!b||b.dataset.logoInstalled)return;b.innerHTML='<img class="dawo-custom-logo" src="dawo-logo.svg" alt="Dawo"><span class="dawo-custom-sub">MIX STUDIO</span>';b.dataset.logoInstalled='1'}
  function mainWave(){const w=document.getElementById('analysisWaveform');if(!w)return;recolor(w);new MutationObserver(()=>recolor(w)).observe(w,{childList:true})}
  function cueStyle(doc){if(doc.getElementById('dawoCueEnergyStyle'))return;const s=doc.createElement('style');s.id='dawoCueEnergyStyle';s.textContent='#waveform,#playerWaveform{align-items:center!important;gap:2px!important}#waveform.energy-spectrum,#playerWaveform.energy-spectrum{background:linear-gradient(180deg,#05090e,#09111a)!important}#waveform.energy-spectrum i,#playerWaveform.energy-spectrum i{background:var(--energy-color)!important;box-shadow:0 0 4px var(--energy-color)!important;border-radius:1px!important;opacity:1!important;min-width:2px}#waveform.energy-spectrum i.past,#playerWaveform.energy-spectrum i.past{filter:brightness(.55) saturate(.8)!important;opacity:.8!important}';doc.head.appendChild(s)}
  function cueFrame(){const frame=document.getElementById('cueflow');if(!frame)return;const setup=()=>{try{const doc=frame.contentDocument;if(!doc)return;cueStyle(doc);const apply=()=>{recolor(doc.getElementById('waveform'));recolor(doc.getElementById('playerWaveform'))};apply();if(!doc.__dawoEnergyObserver){const o=new MutationObserver(apply);o.observe(doc.body,{childList:true,subtree:true});doc.__dawoEnergyObserver=o}}catch(e){console.warn('CueFlow energy spectrum style failed',e)}};frame.addEventListener('load',()=>setTimeout(setup,100));setTimeout(setup,700)}
  function loadCollectionUI(){if(document.querySelector('script[data-dawo-collection-ui]'))return;const s=document.createElement('script');s.src='traktor-collection-ui.js';s.dataset.dawoCollectionUi='1';document.body.appendChild(s)}
  function boot(){mainStyle();brand();mainWave();cueFrame();loadCollectionUI();window.addEventListener('dawo-library-change',()=>setTimeout(()=>recolor(document.getElementById('analysisWaveform')),0))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();